[theme]
primaryColor = "#4C6EF5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = false

[deprecation]
showPyplotGlobalUse = false

[global]
developmentMode = false
